### ISSUE TITLE
TypeError: Cannot read property 'startgroup' of undefined

### ISSUE THREAD

**Issue by monolithed** [npm/gauge#4]
``` js
// progress.js
import Gauge from 'gauge';

export default class Progress extends Gauge {
    constructor (options) {
        super(options);
    }
};
```

``` js
// test.js
import Progress from './progress';

let progress = new Progress('Parsing subjects', 0);
progress.show('test', 1);
```

```
➜ node test.js
/node_modules/gauge/progress-bar.js:174
  values.startgroup = theme.startgroup
                           ^
TypeError: Cannot read property 'startgroup' of undefined
    at ProgressBar.renderTemplate (/node_modules/gauge/progress-bar.js:174:28)
    at drawBar (/node_modules/gauge/progress-bar.js:160:27)
    at ProgressBar.show (/node_modules/gauge/progress-bar.js:149:10)
    at Progress.next (/tools/progress.js:28:8)
    at Object.<anonymous> (/test.js:4:10)
    at Module._compile (module.js:460:26)
    at normalLoader (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by iarna** [comment]
```
let progress = new Progress('Parsing subjects', 0);
```

Those are not valid arguments. Your `Progress` class is descended from `Gauge` and `Gauge` takes:

### var gauge = new Gauge([options], [ansiStream])

It kind of looks like you think you're constructing an `are-we-there-yet` object?

**Comment by monolithed** [comment]
Oh, I forgot `super(options);`
